version: "3.3"

services: 
  app:
    build: 
      context: ./
      dockerfile: Dockerfile
    container_name: seratest-app
    restart: always
    working_dir: /var/www/html
    volumes: 
      - ./:/var/www/html

  nginx:
    image: nginx:1.19-alpine
    container_name: seratest-nginx
    restart: always
    ports: 
      - "7000:80" 
    volumes: 
      - ./:/var/www/html
      - ./nginx/:/etc/nginx/conf.d